#! /usr/bin/env python
import sys
import numpy as np
import ase
from ase.io import read,write
from ase.data.vdw import vdw_radii
from ase.atoms import *
from ase.calculators.neighborlist import *


if len(sys.argv)<1:
	print "Wrong!"
	sys.exit()

scale = 0.78

count=0
newvdw=[]
for i in vdw_radii:
	count+=1
	newvdw.append(i)
newvdw[40]=1.3
newvdw[26]=1.6
CEs=[]
Outnames=[]
bulk_list=[]
subsurf_list=[]
surf_list=[]
CN_12_list=[]
Fe_list=[]

for item in range(1,len(sys.argv)):
	moleculename = sys.argv[item]
	atoms1 = read(moleculename)
	file1 = open(moleculename,'r')
	lines = file1.readlines()
	file1.close()
	outname=moleculename.replace(".xyz","",1)
	Outnames.append(outname)
	count1=0
	BE=0
	count2=0
	for line in lines:
		if count1<=1:
			count1+=1
		else:
			vals=line.split()
			CN_i=float(vals[4])
			name_i=vals[0]
			i = count1-2
			if CN_i<=9:
				surf_list.append(i)
			elif CN_i<12:
				subsurf_list.append(i)
			else:
				bulk_list.append(i)
			count1+=1
	for l in lines:
		if count2<=1:
			count2+=1
		else:
		        vals2=l.split()
                        name_2=vals2[0]
                        n = count2-2
			if name_2=='Fe':
				Fe_list.append(n)
			count2+=1
	total_surf=surf_list+subsurf_list
	Fe_bulk=list(set(bulk_list).intersection(Fe_list))
	Fe_subsurf=list(set(Fe_list).intersection(subsurf_list))
	Fe_surf=list(set(Fe_list).intersection(surf_list))
	Fe_surf_general=Fe_surf+Fe_subsurf	
	
	print '{}'.format(len(Fe_list))
	print 'Number of Fe atoms in bulk is {}'.format(len(Fe_bulk))
	print 'Number of Fe atoms in subsurface is {}'.format(len(Fe_subsurf))
	print 'Number of Fe atoms in surface is {}'.format(len(Fe_surf))
	print 'Number of Fe atoms in general surface is {}'.format(len(Fe_surf_general))
	print 'Number of atoms in surface is {}'.format(len(surf_list))
	print 'Number of atoms in subsuface is {}'.format(len(subsurf_list))
	print 'Number of atoms in bulk is {}'.format(len(bulk_list))
	#print surf_list
