#! /usr/bin/env python
import sys
import numpy as np

if len(sys.argv)<2:
	print "Wrong!"
else:
	for item in sys.argv[1:]:
		file=open(item,'r')
		lines=file.readlines()
		file.close()
		count=0
		CE=0
		for line in lines:
			if count<=1:
				count+=1
			else:
				vals=line.split()
				CN=float(vals[4])
				name=vals[0]
				if name=='Au':
					Ecoh=-2.9641
				elif name=='Cu':
					Ecoh=-3.5196
				elif name=='Ag':
					Ecoh=-2.5814
				elif name=='Zr':
					Ecoh=-7.2453
				CE+= Ecoh*(CN**0.5)/(12**0.5)
				count+=1
		print 'Number of atoms is {}'.format(count-2)
		print 'The CE = {} eV for the {} system'.format(CE/(count-2),item)		
